{% set name = "tsgettoolbox" %}
{% set version = "25.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsgettoolbox-{{ version }}.tar.gz
  sha256: be4e223b86a8be7cc611c21f896e10bddd126facc8150eee7ff9cdcaf6054ce3

build:
  entry_points:
    - tsgettoolbox = tsgettoolbox.tsgettoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - async_retriever
    - beautifulsoup4
    - cftime
    - cltoolbox
    - dapclient
    - geojson
    - haversine
    - httpretty
    - isodate
    - lxml
    - mechanize
    - pydaymet
    - python-dateutil
    - requests
    - siphon
    - suds-community
    - toolbox_utils >=5.0.0,<6.0.0

test:
  imports:
    - tsgettoolbox
  commands:
    - pip check
    - tsgettoolbox --help
  requires:
    - pip

about:
  summary: Will get time series from different sources on the internet
  home: https://pypi.org/project/tsgettoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
