{% set name = "tsgettoolbox" %}
{% set version = "25.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsgettoolbox-{{ version }}.tar.gz
  sha256: c8e450a6420fdf6bea3e737d58fa5c2ad14d5ceea1d20e141f5fb420587a6fa2

build:
  entry_points:
    - tsgettoolbox = tsgettoolbox.tsgettoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - async_retriever
    - cftime
    - cltoolbox
    - dapclient
    - geojson
    - haversine
    - httpretty
    - isodate
    - lxml
    - mechanize
    - pydantic
    - pydaymet
    - requests
    - siphon
    - suds-community
    - toolbox_utils >=3.0.0,<4.0.0
    - zeep

test:
  imports:
    - tsgettoolbox
  commands:
    - pip check
    - tsgettoolbox --help
  requires:
    - pip

about:
  summary: Will get time series from different sources on the internet
  home: https://pypi.org/project/tsgettoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
