{% set name = "tsgettoolbox" %}
{% set version = "26.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsgettoolbox-{{ version }}.tar.gz
  sha256: ad0a821548f9b276f67bf78398a9e046e6651acfc168b9f567b24f1e9a3a6873

build:
  entry_points:
    - tsgettoolbox = tsgettoolbox.tsgettoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - async_retriever
    - beautifulsoup4
    - cftime
    - cltoolbox
    - dateparser
    - geojson
    - haversine
    - httpretty
    - isodate
    - lxml
    - jinja2
    - matplotlib-base >=3.3.2
    - mechanize
    - numpy
    - openpyxl >=3.0.7
    - odfpy >=1.4.1
    - pandas
    - pint !=0.21
    - pint-pandas
    - pydantic
    - pydap
    - pyogrio
    - pytables >=3.6.1
    - pydaymet >=0.17
    - python-calamine
    - python-dateutil
    - pyxlsb >=1.0.8
    - requests
    - scipy
    - siphon
    - suds-community
    - tabulate
    - typing-extensions
    - xlrd >=2.0.1
    - xlsxwriter

test:
  imports:
    - tsgettoolbox
  commands:
    - pip check
    - tsgettoolbox --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Will get time series from different sources on the internet
  home: https://pypi.org/project/tsgettoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
