{% set name = "tsgettoolbox" %}
{% set version = "25.1.12" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsgettoolbox-{{ version }}.tar.gz
  sha256: 8d93065bdee217b90545440b7ad2d872127e296d41465833b222bb051c3c0545

build:
  entry_points:
    - tsgettoolbox = tsgettoolbox.tsgettoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - async_retriever <0.18
    - beautifulsoup4
    - cftime
    - cltoolbox
    - dapclient
    - dateparser
    - geojson
    - haversine
    - httpretty
    - isodate
    - libgdal
    - lxml
    - matplotlib-base >=3.3.2
    - mechanize
    - numpy
    - openpyxl >=3.0.7
    - odfpy >=1.4.1
    - pandas
    - pint
    - pint-pandas
    - pydantic
    - pyogrio
    - pytables >=3.6.1
    - pydaymet
    - python-calamine
    - python-dateutil
    - pyxlsb >=1.0.8
    - rasterio
    - requests
    - scipy
    - siphon
    - suds-community
    - tabulate
    - typing-extensions
    - xlrd >=2.0.1
    - xlsxwriter

test:
  imports:
    - tsgettoolbox
  commands:
    - pip check
    - tsgettoolbox --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Will get time series from different sources on the internet
  home: https://pypi.org/project/tsgettoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
