{% set name = "tsgettoolbox" %}
{% set version = "25.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsgettoolbox-{{ version }}.tar.gz
  sha256: 13424111c1e0c69a8ee36ca3fe6aead4056a5014bad90bba3a8f1532520d769b

build:
  entry_points:
    - tsgettoolbox = tsgettoolbox.tsgettoolbox:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - async_retriever
    - beautifulsoup4
    - cftime
    - cltoolbox
    - dapclient
    - dateparser
    - geojson
    - haversine
    - httpretty
    - isodate
    - lxml
    - matplotlib-base >=3.3.2
    - mechanize
    - numpy
    - pandas
    - openpyxl >=3.0.7
    - odfpy >=1.4.1
    - pint !=0.21
    - pint-pandas
    - pydantic
    - pytables >=3.6.1
    - pydaymet
    - python-calamine
    - python-dateutil
    - pyxlsb >=1.0.8
    - requests
    - scipy
    - siphon
    - suds-community
    - tabulate    
    - typing-extensions
    - xlrd >=2.0.1
    - xlsxwriter

test:
  imports:
    - tsgettoolbox
  commands:
    - pip check
    - tsgettoolbox --help
  requires:
    - pip

about:
  summary: Will get time series from different sources on the internet
  home: https://pypi.org/project/tsgettoolbox/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
