schema_version: 1

context:
  name: tsgettoolbox
  version: "26.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 3a6826460289bdb569e34034446c57ce8b372a8abd5a4cb2e5b98c5eb6d0485d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps
  python:
    entry_points:
      - tsgettoolbox = tsgettoolbox.tsgettoolbox:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - aiodns >3.6.0
    - async_retriever
    - beautifulsoup4
    - cftime
    - cltoolbox >=4.0.4
    - dask-core
    - dateparser
    - deprecated
    - fsspec
    - geojson
    - haversine
    - httpretty
    - isodate
    - jinja2
    - lxml
    - matplotlib-base >=3.3.2
    - mechanize
    - numpy
    - openpyxl >=3.0.7
    - odfpy >=1.4.1
    - packaging
    - pandas
    - pint
    - pint-pandas
    - platformdirs
    - pydantic >=2
    - pydap
    - pyogrio
    - pytables >=3.6.1
    - python-dateutil
    - pyxlsb >=1.0.8
    - requests
    - scipy
    - siphon
    - suds-community
    - tabulate
    - typing-extensions
    - xarray
    - xlrd >=2.0.1
    - xlsxwriter
    - zarr

tests:
  - python:
      imports:
        - tsgettoolbox
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - tsgettoolbox --help

about:
  summary: Will get time series from different sources on the internet
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://pypi.org/project/tsgettoolbox/

extra:
  recipe-maintainers:
    - timcera
